/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customer' : Principal,
  'completed' : boolean,
  'timestamp' : Time,
  'serviceId' : bigint,
  'timeSlot' : string,
  'salonId' : Principal,
}
export interface Review {
  'customer' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Salon {
  'id' : Principal,
  'timeSlots' : Array<string>,
  'name' : string,
  'address' : string,
  'openingHours' : string,
  'contactNumber' : string,
  'services' : Array<Service>,
}
export interface Service { 'id' : bigint, 'name' : string, 'price' : bigint }
export type Time = bigint;
export interface UserProfile {
  'userType' : string,
  'name' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<[string, bigint], undefined>,
  'adminDeleteSalon' : ActorMethod<[Principal], undefined>,
  'adminDeleteUser' : ActorMethod<[Principal], undefined>,
  'adminGetAllBookings' : ActorMethod<[], Array<Booking>>,
  'adminGetAllSalons' : ActorMethod<[], Array<Salon>>,
  'adminGetAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Principal, bigint, string], bigint>,
  'createOrUpdateSalon' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'getAllSalons' : ActorMethod<[], Array<Salon>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerBookings' : ActorMethod<[], Array<Booking>>,
  'getSalon' : ActorMethod<[Principal], [] | [Salon]>,
  'getSalonBookings' : ActorMethod<[], Array<Booking>>,
  'getSalonReviews' : ActorMethod<[Principal], Array<Review>>,
  'getSalonServices' : ActorMethod<[Principal], Array<Service>>,
  'getTimeSlots' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markBookingComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTimeSlots' : ActorMethod<[Array<string>], undefined>,
  'submitReview' : ActorMethod<[Principal, bigint, string], undefined>,
  'updateService' : ActorMethod<[bigint, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];