/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'customer' : IDL.Principal,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'completed' : IDL.Bool,
  'timestamp' : Time,
  'serviceId' : IDL.Nat,
  'lastReminderSent' : IDL.Opt(Time),
  'timeSlot' : IDL.Text,
  'salonId' : IDL.Principal,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Salon = IDL.Record({
  'id' : IDL.Principal,
  'timeSlots' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'contactNumber' : IDL.Text,
  'services' : IDL.Vec(Service),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'bookingConfirmed' : IDL.Null,
  'bookingReminder' : IDL.Null,
  'bookingCancelled' : IDL.Null,
});
export const DeliveryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
});
export const NotificationRecord = IDL.Record({
  'bookingId' : IDL.Nat,
  'notificationType' : NotificationType,
  'recipient' : IDL.Principal,
  'deliveryStatus' : DeliveryStatus,
  'timestamp' : Time,
});
export const Review = IDL.Record({
  'customer' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'adminDeleteSalon' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'adminGetAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'adminGetAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'checkPendingBookingsForReminders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      [],
    ),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, NotificationType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createOrUpdateSalon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getNotificationsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NotificationRecord)],
      ['query'],
    ),
  'getSalon' : IDL.Func([IDL.Principal], [IDL.Opt(Salon)], ['query']),
  'getSalonBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getSalonReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getSalonServices' : IDL.Func([IDL.Principal], [IDL.Vec(Service)], ['query']),
  'getTimeSlots' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
  'setTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'submitReview' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateNotificationStatus' : IDL.Func(
      [IDL.Nat, DeliveryStatus],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'customer' : IDL.Principal,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'completed' : IDL.Bool,
    'timestamp' : Time,
    'serviceId' : IDL.Nat,
    'lastReminderSent' : IDL.Opt(Time),
    'timeSlot' : IDL.Text,
    'salonId' : IDL.Principal,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Salon = IDL.Record({
    'id' : IDL.Principal,
    'timeSlots' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'contactNumber' : IDL.Text,
    'services' : IDL.Vec(Service),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'bookingConfirmed' : IDL.Null,
    'bookingReminder' : IDL.Null,
    'bookingCancelled' : IDL.Null,
  });
  const DeliveryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
  });
  const NotificationRecord = IDL.Record({
    'bookingId' : IDL.Nat,
    'notificationType' : NotificationType,
    'recipient' : IDL.Principal,
    'deliveryStatus' : DeliveryStatus,
    'timestamp' : Time,
  });
  const Review = IDL.Record({
    'customer' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'adminDeleteSalon' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'adminGetAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'adminGetAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'checkPendingBookingsForReminders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        [],
      ),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, NotificationType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createOrUpdateSalon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getNotificationsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getSalon' : IDL.Func([IDL.Principal], [IDL.Opt(Salon)], ['query']),
    'getSalonBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getSalonReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
    'getSalonServices' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getTimeSlots' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
    'setTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'submitReview' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateNotificationStatus' : IDL.Func(
        [IDL.Nat, DeliveryStatus],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };