/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customer' : IDL.Principal,
  'completed' : IDL.Bool,
  'timestamp' : Time,
  'serviceId' : IDL.Nat,
  'timeSlot' : IDL.Text,
  'salonId' : IDL.Principal,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Salon = IDL.Record({
  'id' : IDL.Principal,
  'timeSlots' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'contactNumber' : IDL.Text,
  'services' : IDL.Vec(Service),
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Review = IDL.Record({
  'customer' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'adminDeleteSalon' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'adminGetAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'adminGetAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrUpdateSalon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getSalon' : IDL.Func([IDL.Principal], [IDL.Opt(Salon)], ['query']),
  'getSalonBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getSalonReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getSalonServices' : IDL.Func([IDL.Principal], [IDL.Vec(Service)], ['query']),
  'getTimeSlots' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'submitReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customer' : IDL.Principal,
    'completed' : IDL.Bool,
    'timestamp' : Time,
    'serviceId' : IDL.Nat,
    'timeSlot' : IDL.Text,
    'salonId' : IDL.Principal,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Salon = IDL.Record({
    'id' : IDL.Principal,
    'timeSlots' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'contactNumber' : IDL.Text,
    'services' : IDL.Vec(Service),
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Review = IDL.Record({
    'customer' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'adminDeleteSalon' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'adminGetAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'adminGetAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrUpdateSalon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getSalon' : IDL.Func([IDL.Principal], [IDL.Opt(Salon)], ['query']),
    'getSalonBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getSalonReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
    'getSalonServices' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getTimeSlots' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'submitReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };