/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Salon {
    id: Principal;
    timeSlots: Array<string>;
    name: string;
    address: string;
    openingHours: string;
    contactNumber: string;
    services: Array<Service>;
}
export interface Service {
    id: bigint;
    name: string;
    price: bigint;
}
export interface Booking {
    id: bigint;
    customer: Principal;
    completed: boolean;
    timestamp: Time;
    serviceId: bigint;
    timeSlot: string;
    salonId: Principal;
}
export interface UserProfile {
    userType: string;
    name: string;
    phoneNumber: string;
}
export interface Review {
    customer: Principal;
    comment: string;
    timestamp: Time;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addService(name: string, price: bigint): Promise<void>;
    adminDeleteSalon(salonId: Principal): Promise<void>;
    adminDeleteUser(userId: Principal): Promise<void>;
    adminGetAllBookings(): Promise<Array<Booking>>;
    adminGetAllSalons(): Promise<Array<Salon>>;
    adminGetAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(salonId: Principal, serviceId: bigint, timeSlot: string): Promise<bigint>;
    createOrUpdateSalon(name: string, address: string, contactNumber: string, openingHours: string): Promise<void>;
    getAllSalons(): Promise<Array<Salon>>;
    getBooking(bookingId: bigint): Promise<Booking | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerBookings(): Promise<Array<Booking>>;
    getSalon(salonId: Principal): Promise<Salon | null>;
    getSalonBookings(): Promise<Array<Booking>>;
    getSalonReviews(salonId: Principal): Promise<Array<Review>>;
    getSalonServices(salonId: Principal): Promise<Array<Service>>;
    getTimeSlots(salonId: Principal): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markBookingComplete(bookingId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setTimeSlots(timeSlots: Array<string>): Promise<void>;
    submitReview(salonId: Principal, rating: bigint, comment: string): Promise<void>;
    updateService(serviceId: bigint, name: string, price: bigint): Promise<void>;
}
import type { Booking as _Booking, Salon as _Salon, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addService(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1);
            return result;
        }
    }
    async adminDeleteSalon(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteSalon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteSalon(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminGetAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllBookings();
            return result;
        }
    }
    async adminGetAllSalons(): Promise<Array<Salon>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSalons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSalons();
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: Principal, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateSalon(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateSalon(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateSalon(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllSalons(): Promise<Array<Salon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalons();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBookings();
            return result;
        }
    }
    async getSalon(arg0: Principal): Promise<Salon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalon(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalon(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalonBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonBookings();
            return result;
        }
    }
    async getSalonReviews(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonReviews(arg0);
            return result;
        }
    }
    async getSalonServices(arg0: Principal): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonServices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonServices(arg0);
            return result;
        }
    }
    async getTimeSlots(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlots(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markBookingComplete(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingComplete(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setTimeSlots(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimeSlots(arg0);
            return result;
        }
    }
    async submitReview(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Salon]): Salon | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
